language: go
go:
  - 1.14.x
env:
  - COVER=true
install:
  # Fetch dependencies
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.24.0
  - GO111MODULE=on go mod download
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
before_script:
  - ./cc-test-reporter before-build
script:
  - make test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t gocov
sudo: false
notifications:
  email: false
