language: go
go:
  - 1.7.5
  - 1.8.1
script:
  - curl -s https://raw.githubusercontent.com/pote/gpm/v1.4.0/bin/gpm > gpm
  - chmod +x gpm
  - ./gpm install
  - ./test.sh
sudo: false
notifications:
  email: false
