# This docker-compose file can be used to bring up an example instance of oauth2-proxy
# for manual testing and exploration of features.
# Alongside OAuth2-Proxy, this file also starts Dex to act as the identity provider,
# etcd for storage for Dex, nginx as a reverse proxy and other http services for upstreams
#
# This file is an extension of the main compose file and must be used with it
#    docker-compose -f docker-compose.yaml -f docker-compose-nginx.yaml <command>
# Alternatively:
#    make nginx-<command> (eg make nginx-up, make nginx-down)
#
# Access one of the following URLs to initiate a login flow:
#    - http://oauth2-proxy.localhost
#    - http://httpbin.oauth2-proxy.localhost
#
# The OAuth2 Proxy itself is hosted at http://oauth2-proxy.oauth2-proxy.localhost
#
# Note, the above URLs should work with Chrome, but you may need to add hosts
# entries for other browsers
#    127.0.0.1 oauth2-proxy.localhost
#    127.0.0.1 httpbin.oauth2-proxy.localhost
#    127.0.0.1 oauth2-proxy.oauth2-proxy.localhost
version: '3.0'
services:
  oauth2-proxy:
    ports: []
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy-nginx.cfg:/oauth2-proxy.cfg"
    networks:
      oauth2-proxy: {}
  nginx:
    container_name: nginx
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - 80:80/tcp
    hostname: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      oauth2-proxy: {}
      httpbin: {}
networks:
  oauth2-proxy: {}
