apiVersion: v2
description: K8S example based on https://kind.sigs.k8s.io
name: kubernetes
dependencies:
  - name: dex
    version: 0.19.1
    repository: https://charts.dexidp.io
  - name: oauth2-proxy
    version: &chartVersion 7.9.2
    repository: https://oauth2-proxy.github.io/manifests
  # https://github.com/postmanlabs/httpbin/issues/549 is still in progress, for now using a non-official chart
  - name: httpbin
    version: 1.1.0
    repository: https://conservis.github.io/helm-charts
  - name: hello-world
    version: 1.1.0
    repository: https://conservis.github.io/helm-charts
version: *chartVersion
