name: Continuous Integration

on:
  push:
    branches:
      - '**'
      # - $default-branch
  pull_request:
    branches:
      - '**'
      # - $default-branch

jobs:
  build:
    env:
      COVER: true
      GOPATH: ${{ github.workspace }}
    runs-on: ubuntu-18.04
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Get dependencies
      run: |
        cd src/github.com/${{ github.repository }}
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.24.0
        GO111MODULE=on go mod download
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter

    - name: Lint
      run: |
        cd src/github.com/${{ github.repository }}
        make lint

    - name: Build
      run: |
        cd src/github.com/${{ github.repository }}
        make build

    - name: Test
      run: |
        cd src/github.com/${{ github.repository }}
        ./cc-test-reporter before-build
        make test

    - run: ./cc-test-reporter after-build -t gocov
      if: ${{ always() }}
